# frozen_string_literal: true

source "https://rubygems.org"

# Server
gem "sequel"
gem "sequel_pg"
gem "sequel_tools"
gem "sequel-seed"
# Authentication
gem "bcrypt"
gem "jwt"
# Tasks
gem "rake"
gem "mail"
gem "sinatra"
gem "sinatra-contrib"
# console
gem "pry"
gem "puma"
